const fs = require("fs");
const path = require("path");

const PHOTO_DIR = path.join(__dirname, "../public/images/photos");
const META_PATH = path.join(__dirname, "../src/data/photos.ts");
const OUT_PATH = path.join(__dirname, "../src/data/photos.generated.ts");

const EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

// photos.ts에서 albumMeta 배열을 import하기 위해 간단히 파싱
const metaSrc = fs.readFileSync(META_PATH, "utf-8");

// albumMeta 배열의 각 항목에서 folder, cover 추출
const folderRegex = /folder:\s*"([^"]+)"/g;
const albums = [];
let match;
while ((match = folderRegex.exec(metaSrc)) !== null) {
  albums.push({ folder: match[1] });
}

// cover 값 추출 (있는 경우)
const coverRegex = /cover:\s*(\d+)/g;
let coverIdx = 0;
const coverMap = {};
const lines = metaSrc.split("\n");
let currentFolder = null;
for (const line of lines) {
  const fm = line.match(/folder:\s*"([^"]+)"/);
  if (fm) currentFolder = fm[1];
  const cm = line.match(/cover:\s*(\d+)/);
  if (cm && currentFolder) coverMap[currentFolder] = parseInt(cm[1]);
}

// 각 폴더를 스캔
const result = albums.map(({ folder }) => {
  const dir = path.join(PHOTO_DIR, folder);
  if (!fs.existsSync(dir)) {
    console.warn(`Warning: folder not found: ${folder}`);
    return { folder, photos: [] };
  }
  const photos = fs
    .readdirSync(dir)
    .filter((f) => EXTENSIONS.has(path.extname(f).toLowerCase()))
    .sort();
  return { folder, photos };
});

// photos.generated.ts 생성
const output = `// Auto-generated by scripts/gen-photos.js — do not edit manually
// Run: npm run gen-photos

import { albumMeta } from "./photos";

export interface PhotoAlbumFull {
  title: string;
  date: string;
  folder: string;
  photos: string[];
  cover?: number;
}

const photosByFolder: Record<string, string[]> = ${JSON.stringify(
  Object.fromEntries(result.map((r) => [r.folder, r.photos])),
  null,
  2,
)};

export const albums: PhotoAlbumFull[] = albumMeta.map((meta) => ({
  ...meta,
  photos: photosByFolder[meta.folder] ?? [],
}));
`;

fs.writeFileSync(OUT_PATH, output);

const totalPhotos = result.reduce((sum, r) => sum + r.photos.length, 0);
console.log(`Generated ${OUT_PATH}`);
console.log(`${result.length} albums, ${totalPhotos} photos total`);
