// Auto-generated by scripts/gen-photos.js — do not edit manually
// Run: npm run gen-photos

import { albumMeta } from "./photos";

export interface PhotoAlbumFull {
  title: string;
  date: string;
  folder: string;
  photos: string[];
  cover?: number;
}

const photosByFolder: Record<string, string[]> = {
  "2026-01-컴퓨터시스템소사이어티-동계학술대회,-용평": [
    "KakaoTalk_20260122_103716450_01.jpg",
    "KakaoTalk_20260122_103716450_02.jpg",
    "KakaoTalk_20260122_103716450_03.jpg",
    "KakaoTalk_20260122_103716450_04.jpg",
    "KakaoTalk_20260122_103716450_05.jpg",
    "KakaoTalk_20260122_103716450_06.jpg",
    "KakaoTalk_20260122_103716450_07.jpg",
    "KakaoTalk_20260122_103716450_08.jpg",
    "KakaoTalk_20260122_103716450_09.jpg",
    "KakaoTalk_20260122_103716450_10.jpg"
  ],
  "2025-12-KSC-2025-여수": [
    "IMG_7791.JPG",
    "IMG_7792.JPG",
    "IMG_7793.JPG",
    "IMG_7794.JPG",
    "IMG_7795.JPG",
    "IMG_7796.JPG",
    "IMG_7797.JPG",
    "IMG_7798.JPG",
    "IMG_7799.JPG",
    "IMG_7800.JPG",
    "IMG_7801.JPG",
    "IMG_7803.JPG",
    "IMG_7804.JPG",
    "IMG_7805.JPG",
    "IMG_7806.JPG",
    "IMG_7807.JPG",
    "IMG_7808.JPG",
    "IMG_7809.JPG",
    "IMG_7810.JPG",
    "IMG_7811.JPG",
    "IMG_7812.JPG",
    "IMG_7813.JPG",
    "IMG_7814.JPG",
    "KakaoTalk_20251216_193536831_01.jpg"
  ],
  "2025-08-권예빈-석사-졸업": [
    "KakaoTalk_20250822_132427930.jpg",
    "KakaoTalk_20250822_132427930_01.jpg",
    "KakaoTalk_20250822_132427930_02.jpg",
    "KakaoTalk_20250822_132427930_03.jpg"
  ],
  "2025-07-ISCA-2025,-Tokyo": [
    "KakaoTalk_20250709_144215226_02.jpg",
    "KakaoTalk_20250709_144215226_03.jpg",
    "KakaoTalk_20250709_144215226_04.jpg",
    "KakaoTalk_20250709_144215226_06.jpg",
    "KakaoTalk_20250709_144215226_07.jpg",
    "KakaoTalk_20250709_144215226_08.jpg",
    "KakaoTalk_20250709_144215226_09.jpg",
    "KakaoTalk_20250709_144215226_15.jpg",
    "KakaoTalk_20250709_144215226_16.jpg",
    "KakaoTalk_20250709_144215226_17.jpg",
    "KakaoTalk_20250709_144215226_19.jpg",
    "KakaoTalk_20250709_144215226_24.jpg",
    "KakaoTalk_20250709_144215226_25.jpg"
  ],
  "2025-02-컴퓨터시스템소사이어티-동계학술대회,-용평": [
    "01.jpg",
    "02.jpg",
    "03.jpg",
    "04.jpg",
    "05.jpg",
    "06.jpg",
    "07.jpg",
    "08.jpg",
    "09.jpg"
  ],
  "2024-06-전자공학회,-제주": [
    "01.jpg",
    "02.jpg",
    "03.jpg",
    "04.jpg",
    "05.jpg",
    "06.jpg",
    "07.jpg",
    "08.jpg",
    "09.jpg",
    "10.jpg",
    "11.jpg"
  ],
  "2023-01-박우혁-석사-졸업": [
    "KakaoTalk_Photo_2023-02-15-22-52-45.jpeg"
  ]
};

export const albums: PhotoAlbumFull[] = albumMeta.map((meta) => ({
  ...meta,
  photos: photosByFolder[meta.folder] ?? [],
}));
